Please review pull request to add ham sandwich recipe for lunch
IntroToCode/Spring21_Recipes_Codemates2 pull request #3
Opened 2021-04-04 19:37 UTC by cristinap37

## 🎯 Objective

adding ham sandwich recipe for lunch

## 🛠️ Changes made

added all components of recipe for lunch

## 👥 Who needs to review this Pull Request? 
@IntroToCode/fall20_codemates2 please review!!

2021-04-04 23:37 UTC, alyssamzhu reviewed
@cristinap37 this looks great! i wonder if we can add one more item to beef up the sandwich? perhaps we can add avocado and mixed greens too?

2021-04-05 02:08 UTC, lindalee117 commented
@cristinap37 thanks for this! agree it looks good, but we should also add cutting board to equipment needed. Left the changes for review in the file!

2021-04-05 02:09 UTC, lindalee117 requested changes
@cristinap37 thanks for this! agree it looks good, but we should also add cutting board to equipment needed. Left the changes for review in the file!

2021-04-05 02:09 UTC, lindalee117 commented on lunch/readme.md
> +## Equipment needed: butter knife
Proposal: [add] Cutting board

2021-04-05 02:09 UTC, lindalee117 commented on lunch/readme.md
> +## Ingredients: ham, bread, mayo, lettuce
Proposal: [add] avocado

2021-04-05 02:29 UTC, lindalee117 approved these changes

2021-04-06 03:25 UTC, merged